### ISSUE TITLE
Add Australia as an inventory

### ISSUE THREAD

**Issue by insaindesign** [teslahunt/inventory#15]
Title kinda says it all, but... can we add Australia and states: https://www.tesla.com/en_AU/inventory/new/m3?FleetSalesRegions=New%20South%20Wales

**Comment by bryank91** [comment]
I got it to work by adding 
```  au: { country: 'Australia', language: 'en', market: 'AU', super_region: 'north america' },```
onto `src\inventories\index.js`, however I am not sure how do I get prices so it passes the test. perhaps one of the contributors / owners can help

**Comment by Kikobeats** [comment]
Hello, let me add this in my list of things to do – I want to add it to https://teslahunt.io too 🙂

**Comment by Kikobeats** [comment]
https://t.me/teslahunt_au 🎉

**Comment by Kikobeats** [comment]
https://teslahunt.io/?country=Australia 🎉
