### ISSUE TITLE
Can't be used on us inventory

### ISSUE THREAD

**Issue by ArielS1** [teslahunt/inventory#19]
teslaInventory('us', {
    model: '3',
    condition: 'new'
  }).then(results => console.log(results));

or any other model doesn't return results, even that they are shown in the website

**Comment by Kikobeats** [comment]
Hum, it seems like something in the Tesla API changed. Some petitions are receiving less, results on my local.

I'm going to add some tests there before update the codebase to be sure the change is permanent.
