### ISSUE TITLE
TypeError: teslaInventory(...).then is not a function

### ISSUE THREAD

**Issue by gomezo76** [teslahunt/inventory#23]
Hi,

i'm trying to execute the code snippet provided as example: 
```
const teslaInventory = require('tesla-inventory')

teslaInventory('fr', {
  model: 's',
  condition: 'used'
}).then(results => console.log(results))
```

and here the result i got:
`TypeError: teslaInventory(...).then is not a function`
it seems that `teslaInventory` is not returning a Promise, any clue on this ?

Thanks,

Julien

**Comment by Kikobeats** [comment]
Thanks for reporting ! I updated the example in README 🙏 .
