### ISSUE TITLE
Error: Cannot find module 'got'

### ISSUE THREAD

**Issue by culpeppers** [teslahunt/inventory#9]
Hello,

Whenever attempting to run, both locally or in runkit, the error "Error: Cannot find module 'got'" occurs.

Thanks!

**Comment by Kikobeats** [comment]
Thanks for reporting; can you try again? The latest version should be works fine ([v1.8.16](https://github.com/teslahunt/inventory/commit/6a4abf0fb1ec5df2497eb4a1f309d61187ccb52a))

**Comment by culpeppers** [comment]
Just updated and works perfectly now, thanks!
